networks:
  default:
    name: les-network
    external: true

volumes:
  bin-data:
  obj-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    container_name: les_platform_service
    volumes:
      - .:/app
      - bin-data:/app/bin
      - obj-data:/app/obj
    ports:
      - "8080:80"
      - "9090:90"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;http://+:90
