services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: les_platform_service
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
