FROM mcr.microsoft.com/dotnet/sdk:9.0-bookworm-slim

WORKDIR /app

# Copy csproj file and restore dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy everything else
COPY . ./

EXPOSE 80
EXPOSE 90

# Use dotnet watch to automatically restart on changes
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://+:80;http://+:90"]